# -*- coding: utf-8 -*-
"""Prn2Excel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRnzJTKRiszXjkbMgvlEZrte2BwU3m_A
"""

import pandas as pd

read_file = pd.read_table(r'2020 heating the new PTFE line preliminary.prn')

idx = read_file.loc[read_file['CO2 ppm 191c'] > 400].index[0]

result = read_file.loc[read_file.index[idx:]]

result.to_csv(r'2020 heating the new PTFE line preliminary.csv', index=None)

